# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70af12de843207b79846e9bfce41b5f1c025ae03bd0d992d7deece95359935174676ef777cd1032f3a3fbab8e6f9878814246afdcb26025b1fac763677fcc06a

test:
  secret_key_base: 95eb2bc6b62ccc5ee100c1365a337cd98abcea42c65f0bf5ad99853a3867a5996024c986bcf2b670fe14ca9a4af7e975f0f910fd186c255f2a6e1a4b6820fe6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
